APPLICATION=helloworld

BOARD ?= native
USEMODULE += shell shell_commands ps xtimer periph_gpio_irq  periph_spi  printf_float
RIOTBASE ?= $(CURDIR)/../../../RIOT

DEVELHELP ?= 1

include $(RIOTBASE)/Makefile.include
